version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=supersecreto
    volumes:
      - .:/app
    command: ["./main"]

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
