services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth_service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: authdb
      JWT_SECRET_KEY: supersecretkey
    ports:
      - "8081:8081"

volumes:
  auth_pg_data:
